/**
 * `GET /api/embed/pre-check/qr` — the household's check-in code (C78).
 *
 * ## The household id comes from the session, and only from the session
 *
 * That is the whole security story of this route, and it is short because the
 * payload is short. `pre|M/d/yyyy|householdId` is plain text with nothing
 * signed and nothing secret in it, so the code is not a credential — but it
 * *names* a household, and an endpoint that minted one for an arbitrary id
 * would be a household-enumeration oracle wearing a picture. `claims.sub` →
 * `HouseholdService.resolveUser` → `householdId`; no query parameter is read
 * except the date, and there is a test that passes `?householdId=` and asserts
 * it changed nothing.
 *
 * ## SVG in JSON, not an image response
 *
 * `<img src>` cannot carry an `Authorization` header, so an image response
 * would force the widget through a blob URL and its revoke lifecycle for no
 * gain. The markup is generated by `src/lib/qr/encode.ts` from a string this
 * server built, so injecting it into the shadow root is not an untrusted-HTML
 * question — and it stays crisp at any size in about a kilobyte.
 *
 * ## Off by default at the widget, and why this route still ships
 *
 * `show-qr` defaults to `false`. The payload predates MP's
 * `Events.Allow_QR_Check_In` / `QR_Redirect_Url` columns, which are a different
 * (URL-redirect) mechanism, and whether a *current* check-in station still
 * scans the older barcode cannot be verified from any repo — only at a physical
 * station. So a church turns it on once it has confirmed its own station reads
 * it, and every other church gets a working widget rather than a dead image
 * that support has to explain.
 */

import { NextRequest, NextResponse } from "next/server";
import {
  requireWidgetAuth,
  getCorsHeaders,
  resolveRequestOrigin,
  buildOptionsResponse,
  buildFallbackCorsHeaders,
} from "@/lib/embed/auth";
import { errorResponse } from "@/lib/embed/anonymous-write";
import { checkRateLimit } from "@/lib/embed/rate-limit";
import { HouseholdService } from "@/services/householdService";
import { PreCheckService } from "@/services/preCheckService";
import { encodeQrSvg } from "@/lib/qr/encode";
import { EventDateSchema, type PreCheckQrResponse } from "@mpnext/types";

export async function GET(req: NextRequest) {
  const origin = resolveRequestOrigin(req);

  let claims;
  try {
    claims = await requireWidgetAuth(req, { widget: "pre-check" });
  } catch {
    return errorResponse(
      "auth_required",
      "A valid widget token is required.",
      401,
      buildFallbackCorsHeaders(origin)
    );
  }

  const cors = getCorsHeaders(origin);

  if (claims.sub === "public") {
    return errorResponse(
      "auth_required",
      "Authentication required. Please sign in.",
      401,
      cors
    );
  }

  // Encoding is pure CPU with no MP call behind it, so the bucket exists to
  // bound that rather than to protect a downstream. Fail-open: a store outage
  // should not blank the code on a Sunday morning.
  const limit = await checkRateLimit(`precheck:qr:${claims.sub}`, 60);
  if (!limit.ok) {
    return errorResponse("rate_limited", "Too many requests.", 429, cors);
  }

  try {
    const service = await PreCheckService.getInstance();

    const raw = req.nextUrl.searchParams.get("eventDate");
    let eventDate: string;
    if (raw === null || raw === "") {
      eventDate = await service.resolveDefaultEventDate();
    } else {
      const parsed = EventDateSchema.safeParse(raw);
      if (!parsed.success) {
        return errorResponse(
          "invalid_request",
          "eventDate must be YYYY-MM-DD.",
          400,
          cors
        );
      }
      eventDate = parsed.data;
    }

    const household = await HouseholdService.getInstance();
    const user = await household.resolveUser(claims.sub);

    if (!user || user.householdId == null) {
      return errorResponse(
        "household_not_found",
        "No household is linked to this account.",
        404,
        cors
      );
    }

    // The only two inputs: a date the route validated and a household id the
    // session supplied.
    const payload = service.buildQrPayload(user.householdId, eventDate);

    const body: PreCheckQrResponse = {
      svg: encodeQrSvg(payload, { moduleSize: 4, margin: 4 }),
      eventDate,
      payload,
    };

    // No `Cache-Control`: the response is per-household and a shared cache
    // serving one family's code to another is the one caching failure that
    // matters here.
    return NextResponse.json(body, { status: 200, headers: cors });
  } catch (error) {
    console.error("[pre-check/qr] failed:", error);
    // 500 for an upstream failure, never 502.
    return errorResponse("internal_error", "Internal server error", 500, cors);
  }
}

export async function OPTIONS(req: NextRequest) {
  return buildOptionsResponse(req);
}
