import { MPNextWidget } from "../shared/base-widget";
import { injectExternalCSS, loadScript } from "../shared/cdn-loader";
import { ALL_STYLES } from "./full-calendar-styles";
import {
  renderFilterChips,
  filterEvents,
  renderCardsGrid,
  type CalendarEvent,
  type CalendarFilter,
  type ActiveFilters,
} from "./full-calendar-cards";
import {
  renderMiniCalendar,
  buildEventCountMap,
  type EventCountMap,
} from "./full-calendar-mini-cal";
import { renderDetailModal } from "./full-calendar-modal";
import { renderAgendaList } from "./full-calendar-list";

// ── Constants ──

const FC_VERSION = "7.1.0";

/**
 * FullCalendar 7 theme. Each theme is a separate CDN script (an IIFE over
 * `FullCalendar.Shared` that self-registers into `globalPlugins`) plus a
 * separate stylesheet, so switching themes means changing this constant and
 * re-pinning the two `themes/<name>/...` rows of FC_ASSETS below.
 *
 * `classic` is the closest of the five (classic / monarch / forma / breezy /
 * pulse) to the 6.x look this widget's design was built around.
 */
const FC_THEME = "classic";

const FC_CDN_BASE = `https://cdn.jsdelivr.net/npm/fullcalendar@${FC_VERSION}`;

/**
 * The four pinned FullCalendar 7 assets, each with its Subresource Integrity
 * hash. Two scripts (core, then theme — order matters, the theme IIFE consumes
 * `FullCalendar.Shared`) and two stylesheets.
 *
 * BUMPING FC_VERSION OR FC_THEME REQUIRES RECOMPUTING EVERY HASH HERE. A stale
 * hash makes the browser refuse the asset with no visible error of its own: a
 * bad script hash surfaces as "Failed to load calendar library." on week/grid,
 * and a bad stylesheet hash silently renders an unstyled calendar. Recompute
 * all four in the same edit as the bump:
 *
 *   for f in all/global.js themes/<theme>/global.js \
 *            skeleton.css themes/<theme>/theme.css; do
 *     printf '%-28s sha384-%s\n' "$f" \
 *       "$(curl -sL "https://cdn.jsdelivr.net/npm/fullcalendar@<ver>/$f" \
 *          | openssl dgst -sha384 -binary | openssl base64 -A)"
 *   done
 *
 * Use `all/global.js`, never `all/global.min.js`: v7 publishes no minified
 * global bundle, and jsDelivr's `.min.js` is generated on the fly, so a hash
 * over it would pin CDN-generated bytes rather than author-published ones (the
 * trap that `add-to-calendar-button` fell into — .claude/TODO/15). All four
 * URLs above were verified byte-identical to the npm tarball's own copies.
 *
 * NOTE: `themes/<theme>/palette.css` is deliberately NOT loaded. It defines
 * every theme custom property on `:root`, which never matches inside a shadow
 * tree, while `theme.css` consumes them in 67 of 68 `var()` uses with no
 * fallback — so shipping it yields a calendar with no borders, no today
 * highlight, no event chips and no now-indicator. `FC7_THEME_VARS` in
 * full-calendar-styles.ts supplies the whole contract on `:host` instead, in
 * brand colours.
 */
const FC_ASSETS = {
  coreScript: {
    url: `${FC_CDN_BASE}/all/global.js`,
    sri: "sha384-yWkgABI02aCf8JCYAEQvzSyenUdhkerT0PnFLYOT4ldOYQiZIjZBE0gyAUfNbnRx",
  },
  themeScript: {
    url: `${FC_CDN_BASE}/themes/${FC_THEME}/global.js`,
    sri: "sha384-iB9H+Q8A2/TowGFk6PrYdoCWS0+fVFOgcF66sgg3RXG8EFzCPTVBb40cCd1c0EN+",
  },
  skeletonCss: {
    url: `${FC_CDN_BASE}/skeleton.css`,
    sri: "sha384-k1DJvRPX4MQk68X4A7pdPTF6VV9ocE8YPtbBRNBvjukLp1Zp5KXRiqOVC/JBlFR9",
  },
  themeCss: {
    url: `${FC_CDN_BASE}/themes/${FC_THEME}/theme.css`,
    sri: "sha384-2aGV/VuChm9mQlrfCUhYe/ImdZfZ2Tg0Mjlzv1A37x/ggD+8cSR+3kd11Z0+S1KO",
  },
} as const;

const CARDS_PAGE_SIZE = 12;

const VIEW_TYPES = ["month", "grid", "week", "list", "cards", "calendar"] as const;
type ViewType = (typeof VIEW_TYPES)[number];

const isViewType = (v: string | null): v is ViewType =>
  v !== null && (VIEW_TYPES as readonly string[]).includes(v);

// ── Widget ──

export class FullCalendarWidget extends MPNextWidget {
  private calendarEl: HTMLElement | null = null;
  private calendarInstance: any = null;
  private loading = true;
  private error: string | null = null;
  private currentView: ViewType = "month";
  private showToolbar: boolean = true;
  private isAdmin: boolean = false;
  private allEvents: CalendarEvent[] = [];
  private eventCountsByDate: EventCountMap = {};
  private cardsPage: number = 1;
  private miniCalMonth: Date = new Date();
  private selectedDate: string | null = null;
  private filters: { campuses: CalendarFilter[]; ministries: CalendarFilter[] } = {
    campuses: [],
    ministries: [],
  };
  private activeFilters: ActiveFilters = {
    campusIds: new Set(),
    ministryNames: new Set(),
  };
  private fcLoaded = false;
  private stylesInjected = false;
  /**
   * False until connectedCallback has finished its one and only initialisation
   * pass. Attributes present in the markup are delivered to
   * attributeChangedCallback during upgrade — *before* connectedCallback runs —
   * so acting on them there would initialise the widget a second time.
   * connectedCallback reads `view` and `show-toolbar` off the element itself,
   * so nothing is lost by ignoring those pre-connection callbacks.
   */
  private connectedOnce = false;

  static get observedAttributes() {
    return ["api-host", "view", "show-toolbar"];
  }

  async connectedCallback() {
    // Read view/toolbar attributes
    const viewAttr = this.getAttribute("view");
    if (isViewType(viewAttr)) {
      this.currentView = viewAttr;
    }
    const toolbarAttr = this.getAttribute("show-toolbar");
    if (toolbarAttr === "false") {
      this.showToolbar = false;
    }

    // Await the catalogue before the first paint so a Spanish visitor never
    // sees the toolbar and loading line in English first. Free in practice:
    // the FullCalendar CDN load below is far slower than one same-origin
    // locale chunk.
    await this.initLocale();

    // Inject styles and show loading state
    this.injectStyles(ALL_STYLES);
    this.paint();

    try {
      if (this.needsFullCalendar()) {
        await this.loadFullCalendar();
      }
      this.loading = false;
      this.paint();

      if (this.needsFullCalendar()) {
        this.initCalendar();
      } else {
        await this.loadCardsData();
      }
    } catch (err) {
      console.error("FullCalendarWidget: Failed to initialize:", err);
      this.error = this.t("fullCalendar.initFailed");
      this.loading = false;
      this.paint();
      this.emit("fullCalendarError", {
        error: this.error,
        raw: err instanceof Error ? err.message : String(err),
      });
    } finally {
      this.openAttributeCallbacks();
    }
  }

  /**
   * End of the single initialisation pass: start honouring
   * attributeChangedCallback, and replay anything that changed during the
   * awaits above (the CDN load / first fetch), which was suppressed while the
   * widget was still initialising. In the common case both attributes still
   * match the state we initialised with and this does no work.
   */
  private openAttributeCallbacks(): void {
    // Removed again before the init pass finished — disconnectedCallback has
    // already re-armed the guard and a future re-insert owns the next read.
    if (!this.isConnected) return;
    this.connectedOnce = true;

    const showToolbar = this.getAttribute("show-toolbar") !== "false";
    if (showToolbar !== this.showToolbar) {
      this.showToolbar = showToolbar;
      this.rebuildCurrentView();
    }

    const viewAttr = this.getAttribute("view");
    if (isViewType(viewAttr) && viewAttr !== this.currentView) {
      void this.switchView(viewAttr);
    }
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    this.destroyCalendar();
    // Re-arm the guard: a re-inserted element runs connectedCallback again, so
    // it owns the attribute read again. Attribute changes made while detached
    // are picked up by that pass rather than acted on off-document.
    this.connectedOnce = false;
  }

  attributeChangedCallback(name: string, _old: string | null, next: string | null) {
    // Markup attributes arrive here during upgrade, before connectedCallback.
    // connectedCallback owns the initial read of every attribute, so anything
    // delivered before it has finished is not ours to act on — doing so built a
    // whole second FullCalendar and leaked it.
    if (!this.connectedOnce) return;

    if (name === "view") {
      if (isViewType(next)) {
        this.switchView(next);
      }
    } else if (name === "show-toolbar") {
      this.showToolbar = next !== "false";
      // rebuildCurrentView() owns the render() — on the FullCalendar views the
      // render has to be bracketed by destroy/init, so it cannot happen here.
      this.rebuildCurrentView();
    }
  }

  // ── View Helpers ──

  private needsFullCalendar(): boolean {
    return this.currentView === "week" || this.currentView === "grid";
  }

  /**
   * Load the FullCalendar runtime: two scripts, then the two stylesheets.
   *
   * The scripts are strictly ordered — `themes/<theme>/global.js` is an IIFE
   * that immediately destructures `FullCalendar.Shared`, so the core bundle has
   * to have executed first. `loadScript` dedupes by URL at module scope, so a
   * second widget instance on the page reuses both loads.
   *
   * The stylesheets are per-instance and cannot be deduped that way: v7 ships
   * no CSS inside its JS bundle (6.x injected a `<style>` into `document.head`,
   * which is what the old `adoptCalendarStyles()` cloned), so each shadow root
   * needs its own `<link>`. Hence the `stylesInjected` latch rather than
   * `loadScript`'s shared cache.
   *
   * Awaiting the stylesheets here — rather than in `initCalendar()`, which is
   * synchronous and has three call sites — is what keeps the first paint of
   * the calendar styled. Every `initCalendar()` call either follows an awaited
   * `loadFullCalendar()` or runs when one already completed for this instance.
   */
  private async loadFullCalendar(): Promise<void> {
    if (this.fcLoaded) return;

    await loadScript(FC_ASSETS.coreScript.url, FC_ASSETS.coreScript.sri);
    await loadScript(FC_ASSETS.themeScript.url, FC_ASSETS.themeScript.sri);

    if (!this.stylesInjected) {
      await Promise.all([
        injectExternalCSS(this.root, FC_ASSETS.skeletonCss.url, FC_ASSETS.skeletonCss.sri),
        injectExternalCSS(this.root, FC_ASSETS.themeCss.url, FC_ASSETS.themeCss.sri),
      ]);
      this.stylesInjected = true;
    }

    this.fcLoaded = true;
  }

  private destroyCalendar(): void {
    if (this.calendarInstance) {
      try {
        this.calendarInstance.destroy();
      } catch {
        // Ignore destroy errors
      }
      this.calendarInstance = null;
    }
  }

  // ── View Switching ──

  private async switchView(view: ViewType): Promise<void> {
    if (view === this.currentView) return;

    const wasFC = this.needsFullCalendar();
    this.currentView = view;
    const nowFC = this.needsFullCalendar();

    if (wasFC && !nowFC) {
      // Switching FROM FC to cards/calendar — destroy FC
      this.destroyCalendar();
      this.paint();
      await this.loadCardsData();
    } else if (!wasFC && nowFC) {
      // Switching FROM cards/calendar to FC — need to load FC
      this.loading = true;
      this.paint();
      try {
        await this.loadFullCalendar();
        this.loading = false;
        this.paint();
        this.initCalendar();
      } catch {
        this.error = this.t("fullCalendar.libraryFailed");
        this.loading = false;
        this.paint();
      }
    } else if (wasFC && nowFC) {
      // Switching between FC views
      const fcViewMap: Record<string, string> = {
        grid: "dayGridMonth",
        week: "timeGridWeek",
      };
      this.calendarInstance?.changeView(fcViewMap[view]);
      this.updateToolbarActiveState();
    } else {
      // Switching between cards/calendar
      this.paint();
      this.renderCardsOrCalendarView();
    }

    this.emit("viewChanged", { view });
  }

  // ── Calendar Initialization ──

  private initCalendar(): void {
    const FC = (window as any).FullCalendar;
    if (!FC) {
      this.error = this.t("fullCalendar.libraryUnavailable");
      this.paint();
      return;
    }

    this.calendarEl = this.root.querySelector<HTMLElement>("#nw-fc-mount");
    if (!this.calendarEl) return;

    const fcViewMap: Record<string, string> = {
      grid: "dayGridMonth",
      week: "timeGridWeek",
    };

    this.calendarInstance = new FC.Calendar(this.calendarEl, {
      initialView: fcViewMap[this.currentView] || "dayGridMonth",
      headerToolbar: false, // We use our own custom toolbar
      events: (
        info: { startStr: string; endStr: string },
        successCallback: (events: object[]) => void,
        failureCallback: (error: Error) => void
      ) => {
        this.fetchEvents(info.startStr, info.endStr)
          .then(successCallback)
          .catch(failureCallback);
      },
      eventClick: (info: { event: any }) => {
        const raw: CalendarEvent = info.event.extendedProps._raw;
        this.showEventModal(raw, info.event);
      },
      eventColor: "#004C97",
      height: "auto",
      nowIndicator: true,
      dayMaxEvents: 4,
      eventTimeFormat: {
        hour: "numeric",
        minute: "2-digit",
        meridiem: "short",
      },
      datesSet: (info: { start: Date; end: Date; view: { title: string } }) => {
        // `info.view.title` is unusable in either view. FullCalendar 7 builds
        // it from its own locale data, a CDN asset this widget does not load,
        // so it is always English whatever the page locale; and for
        // timeGridWeek it reports "September 2026" where 6.x reported the day
        // range. Both titles are computed from the dates instead.
        this.updateToolbarTitle(
          this.currentView === "week"
            ? this.formatWeekTitle(info.start, info.end)
            : this.formatMonthTitle(info.start, info.end)
        );
      },
      // No `dayCellDidMount`: the density dots it used to paint were removed
      // (.claude/TODO/39). They only ever ran on `week` — a `timeGridWeek`
      // that already draws every event as a positioned, timed block — and
      // never on its first paint, because the hook fires during the initial
      // render, before FullCalendar has called the `events` option that fills
      // `eventCountsByDate`. The mini calendar keeps its own dots, on a path
      // that runs after the data loads.

      // v7 renamed `eventClassNames` → `eventClass`. The class is ours, not an
      // `fc-*` one: v7's own class names are build-generated hashes (`fc-1q`,
      // `fc-DP`, …) and are not a public API, so the chip rounding and hover
      // lift that used to be `.fc-event` rules hang off this instead.
      eventClass: () => "nw-fc-event",
    });

    this.calendarInstance.render();
  }

  /**
   * "September 2026" for a month grid.
   *
   * Derived from the midpoint of the visible range rather than from `start`:
   * a dayGridMonth range begins on the first day of the week containing the
   * 1st, so `start` itself often falls in the *previous* month (a September
   * grid starts Aug 30). The range always spans four to six whole weeks
   * around one month, so its middle is always inside that month.
   */
  private formatMonthTitle(start: Date, end: Date): string {
    const middle = new Date((start.getTime() + end.getTime()) / 2);
    return this.fmt.date(middle, "monthYear");
  }

  /**
   * "Sep 6 – 12, 2026" for a week. Replaces FullCalendar 7's `view.title`,
   * which collapses a timeGridWeek range to just the month and year (and
   * renders it in English).
   *
   * `fmt.dateRangeCompact` is `Intl.DateTimeFormat.formatRange`, which knows
   * per locale which components the two endpoints share and where to put the
   * separator — "6–12 sept 2026", "6 – 12 de set. de 2026". Collapsing this by
   * hand only works in a month-first locale: `es` and `pt-BR` lead with the day,
   * so a hand-built "Sep 6 – 12, 2026" becomes "6 sept – 12, 2026", where the
   * trailing 12 reads as a second month.
   *
   * `end` is exclusive, per FullCalendar's convention, so the last visible day
   * is `end - 1ms`.
   */
  private formatWeekTitle(start: Date, end: Date): string {
    const last = new Date(end.getTime() - 1);
    return this.fmt.dateRangeCompact(start, last, "medium");
  }

  // ── Data Fetching ──

  private async fetchEvents(start: string, end: string): Promise<object[]> {
    const params = new URLSearchParams({ start, end });

    const res = await this.fetch(`/api/embed/full-calendar?${params}`);

    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      const msg = this.errorText(body);
      this.emit("fullCalendarError", { error: msg });
      throw new Error(msg);
    }

    const data = await res.json();
    const events: CalendarEvent[] = data.events || [];
    this.isAdmin = data.isAdmin || false;

    // Store filters if present
    if (data.filters) {
      this.filters = data.filters;
    }

    // Store events for density dots on FC views
    this.allEvents = events;
    this.eventCountsByDate = buildEventCountMap(events);

    this.emit("calendarLoaded", { count: events.length });

    return events.map((e) => ({
      id: String(e.Event_ID),
      title: e.Event_Title,
      start: e.Event_Start_Date,
      end: e.Event_End_Date,
      color: this.getEventColor(e.Event_Type_ID),
      extendedProps: {
        description: e.Description,
        location: e.Location_Name,
        congregation: e.Congregation_Name,
        eventType: e.Event_Type,
        featured: e.Featured_On_Calendar,
        _raw: e,
      },
    }));
  }

  private async loadCardsData(): Promise<void> {
    try {
      // Fetch current month + 2 months ahead
      const start = new Date();
      start.setDate(1);
      start.setHours(0, 0, 0, 0);
      const end = new Date(start);
      end.setMonth(end.getMonth() + 3);

      const params = new URLSearchParams({
        start: start.toISOString(),
        end: end.toISOString(),
      });

      const res = await this.fetch(`/api/embed/full-calendar?${params}`);
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(this.errorText(body));
      }

      const data = await res.json();
      this.allEvents = data.events || [];
      this.isAdmin = data.isAdmin || false;
      if (data.filters) {
        this.filters = data.filters;
      }
      this.eventCountsByDate = buildEventCountMap(this.allEvents);

      this.emit("calendarLoaded", { count: this.allEvents.length });
      this.renderCardsOrCalendarView();
    } catch (err) {
      console.error("FullCalendarWidget: Failed to load cards data:", err);
      this.emit("fullCalendarError", {
        // `errorText` has already turned an API machine code into a translated
        // sentence; anything else (a dropped connection) becomes the generic
        // network message rather than leaking English.
        error: err instanceof Error ? err.message : this.t("errors.network"),
      });
    }
  }

  // ── Event Color Coding ──

  private getEventColor(typeId: number | null): string {
    const colors: Record<number, string> = {
      1: "#004C97",
      2: "#002855",
      3: "#F1BE48",
      4: "#009CDE",
      5: "#FF6D6A",
    };
    return colors[typeId ?? 0] || "#004C97";
  }

  // ── Event Modal ──

  private async showEventModal(raw: CalendarEvent, fcEvent?: any): Promise<void> {
    this.emit("eventSelected", {
      eventId: raw.Event_ID,
      title: raw.Event_Title,
    });

    // For admin users, fetch fresh detail with admin enrichment
    let event = raw;
    let isAdmin = this.isAdmin;

    if (this.isAdmin) {
      try {
        const res = await this.fetch(
          `/api/embed/full-calendar/${raw.Event_ID}`
        );
        if (res.ok) {
          const data = await res.json();
          event = data.event;
          isAdmin = data.isAdmin;
        }
      } catch {
        // Fall back to existing event data
      }
    }

    const fcEventObj = fcEvent
      ? { start: fcEvent.start, end: fcEvent.end }
      : {
          start: event.Event_Start_Date ? new Date(event.Event_Start_Date) : null,
          end: event.Event_End_Date ? new Date(event.Event_End_Date) : null,
        };

    // Remove existing modal if present
    const existing = this.root.querySelector(".nw-fc-modal-overlay");
    if (existing) existing.remove();

    const modal = renderDetailModal({
      event,
      fcEvent: fcEventObj,
      isAdmin,
      onClose: () => this.closeModal(),
      getEventColor: (typeId) => this.getEventColor(typeId),
      t: this.t,
      fmt: this.fmt,
    });

    this.root.appendChild(modal);
    requestAnimationFrame(() => modal.classList.add("nw-fc-modal-visible"));
  }

  private closeModal(): void {
    const overlay = this.root.querySelector<HTMLElement>(".nw-fc-modal-overlay");
    if (overlay) {
      overlay.classList.remove("nw-fc-modal-visible");
      overlay.addEventListener("transitionend", () => overlay.remove(), { once: true });
    }
  }

  // ── Toolbar ──

  private renderToolbar(): string {
    if (!this.showToolbar) return "";

    const views: { key: ViewType; label: string }[] = [
      { key: "month", label: this.t("fullCalendar.viewMonth") },
      { key: "grid", label: this.t("fullCalendar.viewGrid") },
      { key: "week", label: this.t("fullCalendar.viewWeek") },
      { key: "list", label: this.t("fullCalendar.viewList") },
      { key: "cards", label: this.t("fullCalendar.viewCards") },
      { key: "calendar", label: this.t("fullCalendar.viewCalendar") },
    ];

    const viewButtons = views
      .map(
        (v) =>
          `<button class="nw-fc-toolbar-btn${v.key === this.currentView ? " active" : ""}" data-view="${v.key}">${this.escapeHtml(v.label)}</button>`
      )
      .join("");

    return `
      <div class="nw-fc-toolbar">
        <div class="nw-fc-toolbar-left">
          <button class="nw-fc-toolbar-nav" data-action="prev" aria-label="${this.escapeHtml(this.t("common.previous"))}">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
          </button>
          <button class="nw-fc-toolbar-nav" data-action="next" aria-label="${this.escapeHtml(this.t("common.next"))}">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>
          </button>
          <button class="nw-fc-toolbar-btn" data-action="today">${this.escapeHtml(this.t("fullCalendar.today"))}</button>
        </div>
        <div class="nw-fc-toolbar-center" id="nw-fc-title"></div>
        <div class="nw-fc-toolbar-right">
          ${viewButtons}
        </div>
      </div>
    `;
  }

  private bindToolbarEvents(): void {
    const toolbar = this.root.querySelector(".nw-fc-toolbar");
    if (!toolbar) return;

    toolbar.addEventListener("click", (e) => {
      const btn = (e.target as HTMLElement).closest("button");
      if (!btn) return;

      const action = btn.dataset.action;
      const view = btn.dataset.view as ViewType;

      if (action === "prev") this.handleToolbarPrev();
      else if (action === "next") this.handleToolbarNext();
      else if (action === "today") this.handleToolbarToday();
      else if (view) this.switchView(view);
    });
  }

  private handleToolbarPrev(): void {
    if (this.needsFullCalendar() && this.calendarInstance) {
      this.calendarInstance.prev();
    } else {
      this.miniCalMonth = new Date(
        this.miniCalMonth.getFullYear(),
        this.miniCalMonth.getMonth() - 1,
        1
      );
      this.renderCardsOrCalendarView();
    }
  }

  private handleToolbarNext(): void {
    if (this.needsFullCalendar() && this.calendarInstance) {
      this.calendarInstance.next();
    } else {
      this.miniCalMonth = new Date(
        this.miniCalMonth.getFullYear(),
        this.miniCalMonth.getMonth() + 1,
        1
      );
      this.renderCardsOrCalendarView();
    }
  }

  private handleToolbarToday(): void {
    if (this.needsFullCalendar() && this.calendarInstance) {
      this.calendarInstance.today();
    } else {
      this.miniCalMonth = new Date();
      this.selectedDate = null;
      this.renderCardsOrCalendarView();
    }
  }

  private updateToolbarTitle(title: string): void {
    const el = this.root.querySelector<HTMLElement>("#nw-fc-title");
    if (el) el.textContent = title;
  }

  private updateToolbarActiveState(): void {
    const btns = this.root.querySelectorAll<HTMLElement>(".nw-fc-toolbar-btn[data-view]");
    btns.forEach((btn) => {
      btn.classList.toggle("active", btn.dataset.view === this.currentView);
    });
  }

  // ── Cards/Calendar View Rendering ──

  private renderCardsOrCalendarView(): void {
    const container = this.root.querySelector<HTMLElement>(".nw-fc-container");
    if (!container) return;

    // Clear mount point area
    const mount = container.querySelector("#nw-fc-cards-area");
    if (mount) mount.remove();

    const area = document.createElement("div");
    area.id = "nw-fc-cards-area";

    // Get filtered events
    const filtered = filterEvents(this.allEvents, this.activeFilters);

    // Further filter by selected date if applicable
    let displayEvents = filtered;
    if (this.selectedDate) {
      displayEvents = filtered.filter((e) => {
        const eventDate = e.Event_Start_Date.slice(0, 10);
        return eventDate === this.selectedDate;
      });
    }

    // Update title for cards views
    this.updateToolbarTitle(this.fmt.date(this.miniCalMonth, "monthYear"));

    if (this.currentView === "month") {
      // Full-width mini calendar + card grid below
      const monthPanel = document.createElement("div");
      monthPanel.className = "nw-fc-month-layout";

      monthPanel.appendChild(
        renderMiniCalendar({
          currentMonth: this.miniCalMonth,
          eventsByDate: this.eventCountsByDate,
          selectedDate: this.selectedDate,
          onDateClick: (dateKey) => {
            this.selectedDate = this.selectedDate === dateKey ? null : dateKey;
            this.cardsPage = 1;
            this.renderCardsOrCalendarView();
          },
          onMonthChange: (newMonth) => {
            this.miniCalMonth = newMonth;
            this.renderCardsOrCalendarView();
          },
          t: this.t,
          fmt: this.fmt,
        })
      );

      if (this.filters.campuses.length > 0 || this.filters.ministries.length > 0) {
        monthPanel.appendChild(
          renderFilterChips(
            this.filters,
            this.activeFilters,
            (newFilters) => {
              this.activeFilters = newFilters;
              this.cardsPage = 1;
              this.renderCardsOrCalendarView();
            },
            this.t
          )
        );
      }

      monthPanel.appendChild(
        renderCardsGrid(
          displayEvents,
          this.cardsPage,
          (event) => this.showEventModal(event),
          () => {
            this.cardsPage++;
            this.renderCardsOrCalendarView();
          },
          this.t,
          this.fmt
        )
      );

      area.appendChild(monthPanel);
    } else if (this.currentView === "list") {
      // Custom agenda list view — events grouped by date
      if (this.filters.campuses.length > 0 || this.filters.ministries.length > 0) {
        area.appendChild(
          renderFilterChips(
            this.filters,
            this.activeFilters,
            (newFilters) => {
              this.activeFilters = newFilters;
              this.renderCardsOrCalendarView();
            },
            this.t
          )
        );
      }

      area.appendChild(
        renderAgendaList(
          displayEvents,
          (event) => this.showEventModal(event),
          (typeId) => this.getEventColor(typeId),
          this.t,
          this.fmt
        )
      );
    } else if (this.currentView === "cards") {
      // Filter chips + card grid
      if (this.filters.campuses.length > 0 || this.filters.ministries.length > 0) {
        area.appendChild(
          renderFilterChips(
            this.filters,
            this.activeFilters,
            (newFilters) => {
              this.activeFilters = newFilters;
              this.cardsPage = 1;
              this.renderCardsOrCalendarView();
            },
            this.t
          )
        );
      }

      area.appendChild(
        renderCardsGrid(
          displayEvents,
          this.cardsPage,
          (event) => this.showEventModal(event),
          () => {
            this.cardsPage++;
            this.renderCardsOrCalendarView();
          },
          this.t,
          this.fmt
        )
      );
    } else if (this.currentView === "calendar") {
      // Split layout: mini calendar + cards
      const layout = document.createElement("div");
      layout.className = "nw-fc-split-layout";

      // Mini calendar panel
      const miniPanel = document.createElement("div");
      miniPanel.className = "nw-fc-mini-cal-panel";
      miniPanel.appendChild(
        renderMiniCalendar({
          currentMonth: this.miniCalMonth,
          eventsByDate: this.eventCountsByDate,
          selectedDate: this.selectedDate,
          onDateClick: (dateKey) => {
            this.selectedDate = this.selectedDate === dateKey ? null : dateKey;
            this.cardsPage = 1;
            this.renderCardsOrCalendarView();
          },
          onMonthChange: (newMonth) => {
            this.miniCalMonth = newMonth;
            this.renderCardsOrCalendarView();
          },
          t: this.t,
          fmt: this.fmt,
        })
      );
      layout.appendChild(miniPanel);

      // Cards panel with filters
      const cardsPanel = document.createElement("div");
      cardsPanel.className = "nw-fc-cards-panel";

      if (this.filters.campuses.length > 0 || this.filters.ministries.length > 0) {
        cardsPanel.appendChild(
          renderFilterChips(
            this.filters,
            this.activeFilters,
            (newFilters) => {
              this.activeFilters = newFilters;
              this.cardsPage = 1;
              this.renderCardsOrCalendarView();
            },
            this.t
          )
        );
      }

      cardsPanel.appendChild(
        renderCardsGrid(
          displayEvents,
          this.cardsPage,
          (event) => this.showEventModal(event),
          () => {
            this.cardsPage++;
            this.renderCardsOrCalendarView();
          },
          this.t,
          this.fmt
        )
      );
      layout.appendChild(cardsPanel);

      area.appendChild(layout);
    }

    container.appendChild(area);
  }

  /**
   * Re-render the widget chrome and re-attach whatever view is active.
   *
   * `render()` rewrites `.nw-fc-container`'s innerHTML, which **replaces the
   * `#nw-fc-mount` element** a live FullCalendar instance is bound to. The
   * instance keeps its reference to the now-detached node, so calling
   * `calendarInstance.render()` afterwards paints into an orphan and leaves the
   * fresh mount empty — a silently blank widget, no throw, no error event.
   *
   * FullCalendar has no supported "re-attach to a new element" call, so the
   * only correct sequence is the one `switchView()` already uses when it
   * crosses into the FullCalendar views: destroy → render → init.
   */
  private rebuildCurrentView(): void {
    if (this.needsFullCalendar()) {
      const hadInstance = this.calendarInstance !== null;
      this.destroyCalendar();
      this.paint();
      if (hadInstance) this.initCalendar();
    } else {
      this.paint();
      this.renderCardsOrCalendarView();
    }
  }

  // ── Render ──

  /**
   * The re-render entry point every *external* caller reaches, including the
   * base class's page-wide locale change — which is why it delegates to the
   * full rebuild rather than to `paint()`. A bare repaint orphans a live
   * FullCalendar instance and drops the cards area (see `rebuildCurrentView`),
   * and the locale handler has no way to know which of the six views is up.
   * The internal callers already sequence destroy/init themselves and go
   * straight to `paint()`.
   */
  render(): void {
    this.rebuildCurrentView();
  }

  /** Rewrite the widget chrome. Callers own whatever hangs off it. */
  private paint(): void {
    const container = this.root.querySelector<HTMLElement>(".nw-fc-container");

    if (container) {
      container.innerHTML = this.renderInner();
    } else {
      const wrapper = document.createElement("div");
      wrapper.className = "nw-fc-container";
      wrapper.innerHTML = this.renderInner();
      this.root.appendChild(wrapper);
    }

    this.bindToolbarEvents();
  }

  private renderInner(): string {
    if (this.error) {
      return `
        ${this.renderToolbar()}
        <div class="nw-fc-state nw-fc-error">
          <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
          <p>${this.escapeHtml(this.error)}</p>
        </div>
      `;
    }

    if (this.loading) {
      return `
        ${this.renderToolbar()}
        <div class="nw-fc-state nw-fc-loading">
          <div class="nw-fc-spinner"></div>
          <p>${this.escapeHtml(this.t("fullCalendar.loading"))}</p>
        </div>
      `;
    }

    if (this.needsFullCalendar()) {
      return `
        ${this.renderToolbar()}
        <div id="nw-fc-mount" class="nw-fc-mount"></div>
      `;
    }

    // Cards/Calendar views — the card content is rendered separately via DOM manipulation
    return `
      ${this.renderToolbar()}
    `;
  }

  private escapeHtml(str: string): string {
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }
}

customElements.define("next-full-calendar", FullCalendarWidget);
